# Context:
 #-------------
# Maria needs to check the link between copy number of gene expression for a manuscript on organoids ready for submission (little more information provided)

# Aim:
 #-------------
# Check correlation between absolute copy number and gene expression in 18 samples.
# For a set of genes Maria is interested in,
# or across the genome depending on Maria's decision

# Note:
 #-------------
# the code comprises chunks for featureCounts and or kallisto text output that
# we do  not need, but want to keep until the project is finished. 

# Data sets
 #-------------

# Sample sheet
# samples.xlsx: sample sheet with the two sets of sample IDs used: one for CN, the other for gene expression
# samples.csv: text version of samples.xlsx

# CN:
# organoidAbsolute_SegTable.txt: absolute copy number for 18 samples (columns) and 30 kb bins along autosomes 
# organoidAbsolute_geneList.txt: table in the long format with genes of interest their coordinates, absolute copy number ('segVal') and sample ('sample')

# gene expression
# featureCounts, now replaced with kallisto 
# kallisto output in Kallisto2

# Functions
 #-------------

 #------------------------------------------------------------------------------
matFromFeatureCounts <- function (sampleTable, directory = ".", ignoreRank = FALSE, ...) 
 #------------------------------------------------------------------------------
{
	# IN: sampleTable, see DESeqDataSetFromHTSeqCount()
	#	at https://www.rdocumentation.org/packages/DESeq2/versions/1.12.3/topics/DESeqDataSet-class
	#	The first column is the sample name, the second column the file name of the count file generated by htseq-count

	# read files in:
	l <- lapply(as.character(sampleTable[, 2]), function(fn) read.table(file.path(directory, fn), skip=2))
	# check that all gene names are in the same order:
	if (!all(sapply(l, function(a) all(a$V1 == l[[1]]$V1)))) 
		stop("Gene IDs (first column) differ between files.")
	# Get counts
	tbl <- sapply(l, function(a) a$V7)
	# tidy:
	colnames(tbl) <- sampleTable[, 1]
	rownames(tbl) <- l[[1]]$V1
	rownames(sampleTable) <- sampleTable[, 1]
	return(dds)
}



# Packages
 #-------------
library(dplyr)
library(GenomicRanges)

# Variables
 #-------------
projName <- "20191218_ViasM_BJ_orgaBrs"
projDir <- "~/MyProjectsSvn/SvnRepoForStdRnaSeq/Brenton/ViasM/20191218_ViasM_BJ_orgaBrs/trunk"
#projDir <- "/mnt/scratchb/bioinformatics/baller01/20191218_ViasM_BJ_orgaBrs/Data"
setwd(projDir)

# Assess correlation between gene expression and copy number.
 #-------------

setwd("Data")

# Read sample sheet in
 #-------------
# samples.csv has three columns:
# organoid_name;
# JBLAB-number; # eg JBLAB-19902
# OV04_number
tmpFn <- "samples.csv"
splSht <- read.table(tmpFn, sep=";", header=TRUE)
# add name of fatureCounts file. Mind that is not used anymore, now using Kallisto's TPM.
# keeping featureCounts in code though, to compare with kallisto if need be
splSht <- splSht %>% mutate(SampleName=gsub("-","",JBLAB.number)) %>%
	mutate(ftcFn=paste0(SampleName,".featureCounts.gz"))

# Read CNV data in:
 #-------------
# 1: the whole table
tmpFn <- "organoidAbsolute_SegTable.txt"
absCnDf <- read.table(tmpFn, sep="\t", header=TRUE)

# Make GRanges from first column
 #-------------
# Get gene list
# Get overlap

# derive data frame to feed makeGRangesFromDataFrame()
tmpl <- strsplit(as.character(absCnDf[,1]),"[:-]")
cnSeg <- do.call(rbind, lapply(tmpl,as.numeric))
colnames(cnSeg) <- c("chr", "start", "end")
# make GRanges, keeping the CN values.
cnSegRg <- makeGRangesFromDataFrame(cbind(cnSeg,absCnDf[,-1]), keep.extra.columns=TRUE)

# Read gene list in.
 #-------------
tmpFn <- "organoidAbsolute_geneList.txt"
geneDf <- read.table(tmpFn, sep="\t", header=TRUE)
geneDfRg <- makeGRangesFromDataFrame(geneDf)

# concat featureCount outcome for each sample into a single table:
 #-------------
if(FALSE) # not using featureConts anymore
{
dd <- matFromFeatureCounts(sampleTable = splSht[,c("SampleName","ftcFn")],
		     directory = "samplebam")
}

# read kallisto data in
 #-------------
# and get gene-level TPM
# so first need transcript to gene keys.

setwd(projDir)

# gene annotation for kallisto
 #-------------------------
# data.frame called tx2gene with two columns: 1) transcript ID and 2) gene ID

# See tximport vignette:
# Note: if you are using an Ensembl transcriptome, the easiest way to create the tx2gene data.frame is to use the ensembldb packages. The annotation packages can be found by version number, and use the pattern EnsDb.Hsapiens.vXX. The transcripts function can be used with return.type="DataFrame", in order to obtain something like the df object constructed in the code chunk above. See the ensembldb package vignette for more details.

 # projDir
ref_dir <- 'KallistoIdx/homo_sapiens'
gtf.file <- file.path(ref_dir, "Homo_sapiens.GRCh38.96.gtf.gz")
sqlite_file <- 'Homo_sapiens.GRCh38.96.sqlite'
sqlite_path <- file.path(ref_dir, sqlite_file)

if(!file.exists(sqlite_path)) {
    ## generate the SQLite database file
    ensembldb::ensDbFromGtf(gtf=gtf.file, path=ref_dir, outfile=sqlite_file)
}
EnsDb.Hsapiens.v96 <- ensembldb::EnsDb(sqlite_file)

# Genes, used to annotated the TPM matrix to send to Maria
ag <- ensembldb::genes(EnsDb.Hsapiens.v96, filter=list(AnnotationFilter::GeneBiotypeFilter('protein_coding')), return.type="DataFrame") 
ag

# Transcripts:
Tx <- ensembldb::transcripts(EnsDb.Hsapiens.v96,
                       columns = c("tx_id", "gene_id"),
				  return.type="DataFrame")
##head(Tx)

# Write table to file, for reference
tmpFn <- file.path(ref_dir, "Homo_sapiens.GRCh38.96.txt")
write.table(Tx, file=tmpFn, sep=",", row.names = FALSE)
rm(Tx)

# read that transcript-gene table in
# (no need here really, but will only write the table above once)
tx2gene <- readr::read_csv(tmpFn)
head(tx2gene)

# Kallisto with abundance.h5
 #-------------------------
setwd(projDir)

# have names of files to read in:
files <- file.path("Kallisto2", splSht$JBLAB.number, "abundance.h5")
names(files) <- splSht$SampleName

# collapse transcript counts into gene counts:
# "We can avoid gene-level summarization by setting txOut=TRUE, giving the
#original transcript level estimates as a list of matrices."
# with txOut = FALSE and passing tx2gene
txi.kallisto <- tximport(files, type = "kallisto", txOut = FALSE, tx2gene = tx2gene, ignoreTxVersion = TRUE)
head(txi.kallisto$counts)

# Kallisto with with TSV files
 #-------------------------
# need tx2gene
# keep code here for future use (kallisto is droppping hdf5)
iif(FALSE)
{
files <- file.path("Kallisto2", c("JBLAB-19903","JBLAB-19920"), "abundance.tsv")
names(files) <- c("JBLAB-19903","JBLAB-19920")

txi.kallisto.tsv <- tximport(files, type = "kallisto", tx2gene = tx2gene, ignoreAfterBar = TRUE)
head(txi.kallisto.tsv$counts)
}

if(FALSE) # feature counts
{
# Note: if you are using an Ensembl transcriptome, the easiest way to create the tx2gene data.frame is to use the ensembldb packages. The annotation packages can be found by version number, and use the pattern EnsDb.Hsapiens.vXX. The transcripts function can be used with return.type="DataFrame", in order to obtain something like the df object constructed in the code chunk above. See the ensembldb package vignette for more details.

samples <- read.table(file.path(dir, "samples.txt"), header = TRUE)
samples

# concat featureCount outcome for each sample into a single table:
dd <- matFromFeatureCounts(sampleTable = splSht[,c("SampleName","ftcFn")],
		     directory = "samplebam")
}

# merge TPM matrix and gene annotation
 #-------------------------
tpmMat <- txi.kallisto$counts %>%
	data.frame() %>%
	tibble::rownames_to_column("gene_id") %>%
	dplyr::left_join(data.frame(ag), by="gene_id")

tpmMat <- tpmMat %>% select(colnames(ag), starts_with('JBLAB')) %>%
	select(-seq_coord_system)
tpmMat <- tpmMat %>% mutate_if(is.numeric, round, 1)
# Write the TPM matrix to file:
tmpFn <- sprintf("%s/TpmMat/%s_tpm.csv", projDir, projName)
write.csv(tpmMat, file=tmpFn, row.names = FALSE)

# correlation gene expression and CNV.
 #-------------------------

# format the TPM matrix
 #-------------
# geneDf uses 'sample' eg 119025org, aka 'organoid_name' in splSht
# TPM:
genesToKeep <- as.character(unique(geneDf$Gene))
tpmMatOrig <- tpmMat 

tpmMat <- tpmMat %>% filter(gene_name %in% genesToKeep) %>%
	select(gene_name, colnames((txi.kallisto$counts)))

# convert TPM matrix to long format to match that keeping CN sent by Maria:
tpmMatLong <- tpmMat %>% tidyr::pivot_longer(-gene_name, names_to = "SampleName", values_to = "tpm")

# merge with CN matrix, using {gene_name, SampleName} IDs.
 #-------------
geneDfOrig <- geneDf
geneDfOrig$sample <- as.character(geneDfOrig$sample)

geneDf <- geneDfOrig %>% mutate(organoid_name = sample) %>%
	left_join(splSht[, c("organoid_name", "SampleName")], by="organoid_name")

geneDf2 <- geneDf %>% select(Gene, segVal, SampleName) %>%
	mutate(gene_name = Gene) %>%
	left_join(tpmMatLong, by=c("gene_name", "SampleName"))

# gene of interest:
 #-------------

# plot single gene
if(FALSE) # single gene
{
tmpCn <- geneDf %>% filter(Gene == "BRCA1") %>% pull(segVal)

library(ggplot2)
tmpdf <- geneDf2 %>% filter(Gene == "BRCA1")

#p <- ggplot(tmpdf, aes(tpm, segVal))
p <- ggplot(tmpdf, aes(segVal, tpm))
p + geom_point()
}

# plot all genes of interest at once.
# so far 42,
# shown on 6 columns
# setting the upper bound of the axes to the 90th quantile

# axes limits:
xlim <- c(0, quantile(geneDf2$segVal, probs=0.95))
ylim <- c(0, quantile(geneDf2$tpm, probs=0.95))

# plot:
p <- ggplot(geneDf2, aes(segVal, tpm))
p <- p + geom_point()
p + facet_wrap(~Gene, ncol=6)

p <- p + coord_cartesian(xlim=xlim, ylim=ylim)
p <- p + facet_wrap(~Gene, ncol=6)

# write plot to file
tmpFn <- sprintf("%s/TpmMat/tmpVsSegValInGeneList.png", projDir)
ggsave(tmpFn, plot=p, width = 6*4, height = 7*4, units = "cm")

# write geneDf2 to file
geneDf2 <- geneDf2 %>% mutate_if(is.numeric, round, 1)
tmpFn <- sprintf("%s/TpmMat/tmpVsSegValInGeneList.csv", projDir)
write.csv(geneDf2, file=tmpFn, row.names = FALSE)
